cargo-features = ["edition2021"]

[package]
name = "gcrypt-src"
version = "19.0.0+1.9.3"
edition = "2021"

[dependencies]
ffi-tools = { version = "0.1", git = "https://github.com/byhowe/ffi-tools-rs.git" }
