cargo-features = ["edition2021"]

[package]
name = "gcrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
gcrypt-sys = { version = "0.1", path = "../gcrypt-sys" }
gpgrt = { version = "0.1", git = "https://github.com/byhowe/gpgrt-rs.git" }
